version: '3.8'

services:
  web:
    build: ./django_food_truck
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_food_truck/:/usr/src/django_food_truck/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_food_truck
      - POSTGRES_PASSWORD=django_food_truck
      - POSTGRES_DB=django_food_truck

volumes:
  postgres_data: