# Generated by Django 4.2.7 on 2023-12-01 20:59

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField(null=True, verbose_name='Location ID')),
                ('applicant', models.TextField(null=True, verbose_name='Applicant')),
                ('facility_type', models.CharField(choices=[('Push Cart', 'Push Cart'), ('Truck', 'Truck')], max_length=50, null=True, verbose_name='Facility Type')),
                ('cnn', models.IntegerField(null=True, verbose_name='CNN')),
                ('location_description', models.TextField(null=True, verbose_name='Location Description')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('blocklot', models.CharField(max_length=20, null=True, verbose_name='Block Lot')),
                ('block', models.CharField(max_length=10, null=True, verbose_name='Block')),
                ('lot', models.CharField(max_length=10, null=True, verbose_name='Lot')),
                ('permit', models.CharField(max_length=20, null=True, verbose_name='Permit')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REQUESTED', 'Requested')], max_length=20, null=True, verbose_name='Status')),
                ('food_items', models.TextField(null=True, verbose_name='Food Items')),
                ('x', models.FloatField(null=True, verbose_name='X')),
                ('y', models.FloatField(null=True, verbose_name='Y')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
                ('schedule', models.URLField(null=True, validators=[django.core.validators.URLValidator()], verbose_name='Schedule')),
                ('dayshours', models.TextField(null=True, verbose_name='Days/Hours')),
                ('noisent', models.DateTimeField(null=True, verbose_name='NOI Sent')),
                ('approved', models.DateTimeField(null=True, verbose_name='Approved')),
                ('received', models.DateTimeField(null=True, verbose_name='Received')),
                ('prior_permit', models.TextField(null=True, verbose_name='Prior Permit')),
                ('expiration_date', models.DateTimeField(null=True, verbose_name='Expiration Date')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326, verbose_name='Location')),
                ('fire_prevention_districts', models.IntegerField(null=True, verbose_name='Fire Prevention Districts')),
                ('police_districts', models.IntegerField(null=True, verbose_name='Police Districts')),
                ('supervisor_districts', models.IntegerField(null=True, verbose_name='Supervisor Districts')),
                ('zip_codes', models.IntegerField(null=True, verbose_name='ZIP Codes')),
                ('neighborhoods_old', models.IntegerField(null=True, verbose_name='Neighborhoods (Old)')),
            ],
            options={
                'verbose_name_plural': 'Food Trucks',
            },
        ),
    ]
